spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  #data.sal 파일 읽어주는 용도
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  #jpa page 1부터 파라미터 시작 하겠다는 설정
 # 테스트 환경에서 안되는 이유: 웹 요청이 아니기 떄문에 . 웹 요청이 들어와야 적용됨.
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
        max-page-size: 2000

  datasource:
    url: jdbc:h2:mem:zzamuni
    username: sa
    password:
    driver-class-name: org.h2.Driver


zzamuni:
  jwt-key : k4CJXNYNTj6PjNj6NQV/Hxm+Rdz+Z/ldEW0ROC0Ww/VbDNm/SoGPL2/TrKVG9a1D
