### 테스트 요청

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzE5NDEwMTkzfQ.0C2XVwmILHPRpA430RIE3VYjO79mZ19b_UAjNdeoU8slABQ6Gvk3HjhTDSDBqHve
